'Central Bronx': [10453, 10457, 10460]
'Bronx Park and Fordham'
'High Bridge and Morrisania'
'Hunts Point and Mott Haven'
'Kingsbridge and Riverdale'
'Northeast Bronx'
'Southeast Bronx'
'Central Brooklyn'
'Southwest Brooklyn'
'Borough Park'
'Canarsie and Flatlands'
'Southern Brooklyn'
'Northwest Brooklyn'
'Flatbush'
'East New York and New Lots'
'Greenpoint'
'Sunset Park'
'Bushwick and Williamsburg'
'Central Harlem'
'Chelsea and Clinton'
'East Harlem'
'Gramercy Park and Murray Hill'
'Greenwich Village and Soho'
'Lower Manhattan'
'Lower East Side'
'Upper East Side'
'Upper West Side'
'Inwood and Washington Heights'
'Northeast Queens'
'North Queens'
'Central Queens'
'Jamaica'
'Northwest Queens'
'West Central Queens'
'Rockaways'
'Southeast Queens'
'Southwest Queens'
'West Queens'
'Port Richmond'
'South Shore'
'Stapleton and St. George': [10301, 10304, 10305]
'Mid-Island': [10314]
