# Generated by Django 2.1.7 on 2019-07-10 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='advertises_fee',
            new_name='advertisesNoFee',
        ),
        migrations.RenameField(
            model_name='apartment',
            old_name='has_image',
            new_name='hasImage',
        ),
        migrations.RenameField(
            model_name='apartment',
            old_name='has_map',
            new_name='hasMap',
        ),
        migrations.RenameField(
            model_name='apartment',
            old_name='includes_area',
            new_name='includesArea',
        ),
        migrations.RenameField(
            model_name='apartment',
            old_name='is_repost',
            new_name='isRepost',
        ),
    ]
