# Generated by Django 2.1.7 on 2019-07-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20190710_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='area',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
