# Generated by Django 2.1.7 on 2019-07-10 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20190710_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='area',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=10, null=True),
        ),
    ]
