# Generated by Django 2.1.7 on 2019-07-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20190710_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='bedrooms',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='bikeScore',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='transitScore',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='walkScore',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
