# Generated by Django 2.1.7 on 2019-07-10 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20190710_1727'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='apartment',
            unique_together={('name', 'address')},
        ),
    ]
