# Generated by Django 2.1.7 on 2019-07-11 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20190710_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='advertisesNoFee',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='area',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='bikeScore',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='distanceToNearestIntersection',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='hasImage',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='hasMap',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='includesArea',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='isRepost',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='postalCode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='sideOfStreet',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='transitScore',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='walkScore',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
