# Generated by Django 2.1.7 on 2019-07-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20190714_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='borough',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
