# Generated by Django 2.1.7 on 2019-07-22 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_remove_apartment_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='advertisesNoFee',
            new_name='advertises_no_fee',
        ),
        migrations.RenameField(
            model_name='apartment',
            old_name='bikeScore',
            new_name='bike_score',
        ),
        migrations.RenameField(
            model_name='apartment',
            old_name='distanceToNearestIntersection',
            new_name='distance_to_nearest_intersection',
        ),
        migrations.RenameField(
            model_name='apartment',
            old_name='hasImage',
            new_name='has_image',
        ),
        migrations.RenameField(
            model_name='apartment',
            old_name='hasMap',
            new_name='has_map',
        ),
        migrations.RenameField(
            model_name='apartment',
            old_name='includesArea',
            new_name='includes_area',
        ),
        migrations.RenameField(
            model_name='apartment',
            old_name='isRepost',
            new_name='is_repost',
        ),
        migrations.RenameField(
            model_name='apartment',
            old_name='postalCode',
            new_name='postal_code',
        ),
        migrations.RenameField(
            model_name='apartment',
            old_name='sideOfStreet',
            new_name='side_of_street',
        ),
        migrations.RenameField(
            model_name='apartment',
            old_name='transitScore',
            new_name='transit_score',
        ),
        migrations.RenameField(
            model_name='apartment',
            old_name='walkScore',
            new_name='walk_score',
        ),
    ]
